### ISSUE TITLE
Падает на iOS

### ISSUE THREAD

**Issue by RavisMsk** [yandexmobile/metrica-sdk-ios#1]
Получаю exception при вызове:
[YMMCounter startWithAPIKey:<NSUInteger>];

Ругань:
-[NSBundle yx_appShortVersion]: unrecognized selector sent to instance 0xab6cb10

**Comment by MaximFad** [comment]
в общем да проблема решаемая: выбираете таргет раздел Build Settings -> Other Linker Flags, добавлением -ObjC

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 13407273. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp15.07.2021, 01:05, "Maxim Fadeichev" ***@***.***>:
в общем да проблема решаемая: выбираете таргет раздел Build Settings -> Other Linker Flags, добавлением -ObjC
