### ISSUE TITLE
Open deeplinks в приложении а не в вебвью

### ISSUE THREAD

**Issue by KatyaUzbekova** [yandexmobile/metrica-sdk-ios#101]
В каком методе, и как можно обработать ссылку в уведомлении, что бы открыть ссылку в приложении?

Схема ссылки открывается в приложении, только через уведомление открывается и в приложении и в вебью

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 17386072. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp19.05.2022, 17:10, "KatyaUzbekova" ***@***.***>:
В каком методе, и как можно обработать ссылку в уведомлении, что бы открыть ссылку в приложении?
Схема ссылки открывается в приложении, только через уведомление открывается и в приложении и в вебью
