### ISSUE TITLE
⛔️Undefined symbol: _OBJC_CLASS_$_YMMEnvironmentService (M1) 

### ISSUE THREAD

**Issue by tesum** [yandexmobile/metrica-sdk-ios#103]
Привет, в проекте используется метрика через pod, хотим перенести на SPM в отдельный сервисный модуль, но Notification Extension при компиляции выдает ошибки:

`⛔️ Undefined symbol: _OBJC_CLASS_$_YMMEnvironmentService`
`⛔️ Undefined symbol: _kYMMExternalChannel`
`⛔️ Undefined symbol: _kYMMInternalChannel`

Пакеты:
`.package(url: "https://github.com/yandexmobile/metrica-sdk-ios.git", exact: "3.17.0"),`
`.package(url: "https://github.com/yandexmobile/metrica-push-sdk-ios.git", exact: "1.0.0"),`

C более новыми версиями также.

Можете подсказать с чем может быть связано?

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 18652269. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp08.08.2022, 14:24, "tesum" ***@***.***>:
Привет, в проекте используется метрика через pod, хотим перенести на SPM в отдельный сервисный модуль, но Notification Extension при компиляции выдает ошибки:
⛔️ Undefined symbol: OBJC_CLASS$_YMMEnvironmentService
⛔️ Undefined symbol: _kYMMExternalChannel
⛔️ Undefined symbol: _kYMMInternalChannel
Можете подсказать с чем может быть связано?
