### ISSUE TITLE
The app references non-public selectors in Payload 

### ISSUE THREAD

**Issue by jedi-tones** [yandexmobile/metrica-sdk-ios#104]
I successfully submit the ipa file to the App Store using Application Loader.
But it shows the warning - 
`The app references non-public selectors in Payload/ .../YandexMobileMetrica.framework/YandexMobileMetrica: future, resolve:`

Xcode Version 14.0 (14A309)

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 19174788. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp13.09.2022, 14:17, "Denis Shchigolev" ***@***.***>:
I successfully submit the ipa file to the App Store using Application Loader.
But it shows the warning -
The app references non-public selectors in Payload/ .../YandexMobileMetrica.framework/YandexMobileMetrica: future, resolve:
Xcode Version 14.0 (14A309)

**Comment by GLinnik21** [comment]
> I successfully submit the ipa file to the App Store using Application Loader. But it shows the warning - `The app references non-public selectors in Payload/ .../YandexMobileMetrica.framework/YandexMobileMetrica: future, resolve:`
> 
> Xcode Version 14.0 (14A309)

Hi! 
Thank you for the report! Does Apple allow to release an application to the store with this warning?

**Comment by GLinnik21** [comment]
As far as I understood from [Developer Forums](https://developer.apple.com/forums/thread/707350?answerId=716001022#716001022), there is some kind of issue on Apple's backend, so we can't do anything from our side.
