### ISSUE TITLE
Not working preview Xcode 14 because Xcode can't find executable path YandexMobileMetrica

### ISSUE THREAD

**Issue by kos-tya** [yandexmobile/metrica-sdk-ios#106]
Привет! 
При попытке собрать превьюху в новом Xcode 14 вылетает ошибка, с указанием метрики, мол из-за нее проблемы, без нее превью отображается. 

<img width="556" alt="image" src="https://user-images.githubusercontent.com/85481954/190220921-bc7cef9e-05e7-4328-a6e3-afc70cc0ddaf.png">

```HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x00000002d8b628f0):'YandexMobileMetrica'>)
```

Версия SDK 4.2.0

**Comment by Shishani58** [comment]
Подтверждаю проблему.

**Comment by GLinnik21** [comment]
Привет! 
Да, действительно такая проблема появляется на Xcode 14. Это очень похоже на баг самого Xcode, так как множество пользователей столкнулись с такими же проблемами, используя другие библиотеки: [Developer Forums](https://developer.apple.com/forums/thread/707569). Можно было бы предположить, что Xcode пытается подключить нашу динамическую библиотеку как статическую, однако мы проверили, что оно выдает эту же ошибку если локально подключить статический `.xcframework`. 
Как советует то же комьюнити в Developer Forums, лучшее, что можно сейчас сделать – это отключить мешающие пакеты пока требуется функция Preview. Так же следует зарепортить эту проблему в https://feedbackassistant.apple.com, чтобы Apple быстрее исправил это на своей стороне.

**Comment by GLinnik21** [comment]
Кажется на Xcode 14.1 Beta 2 проблемы больше не наблюдается
