### ISSUE TITLE
Ошибка при публикации приложения

### ISSUE THREAD

**Issue by nikitaskobelkin** [yandexmobile/metrica-sdk-ios#108]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/47354437/191863323-ef9a343b-a620-44ab-a1c1-ee1f877ad91f.png">

**Comment by nikitaskobelkin** [comment]
The app references non-public selectors in Payload/
b/Frameworks/
YandexMobileMetrica.framework/YandexMobileMetrica: future, resolve:

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 19309350. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp23.09.2022, 01:37, "Nikita Romanovich" ***@***.***>:

**Comment by GLinnik21** [comment]
Duplicate of #104
