### ISSUE TITLE
Warning in Xcode

### ISSUE THREAD

**Issue by RublevIgor123** [yandexmobile/metrica-sdk-ios#110]
Xcode версия: Version 14.0.1 (14A400).
Pod версия: pod 'YandexMobileMetrica', '~> 4.4.0'.

Проблема: висит варнинг в классе AppDelegate.swift на строке @main.
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

Я нигде не юзаю CLLocationManager, только в вашем поде это есть.
Пруфы смогу скинуть куда скажете. Косяк мелкий, и надеюсь быстро пофиксите, просто решил сообщить сразу как увидел.

Решение:
https://stackoverflow.com/questions/73805219/main-thread-warning-with-cllocationmanager-locationservicesenabled

**Comment by Sergey70** [comment]
Спасибо за обращение.

**Comment by RublevIgor123** [comment]
пруфы [тут](https://drive.google.com/drive/folders/1W8V3WitmlDOzd_T0uLziPEohCBJAD0QY?usp=sharing)

**Comment by GLinnik21** [comment]
Спасибо! Проблема будет исправлена в следующем релизе.
