### ISSUE TITLE
Не могу добавить в оба target

### ISSUE THREAD

**Issue by vkhadyka** [yandexmobile/metrica-sdk-ios#111]
У меня есть 2 таргета в приложении. 
И я хочу добавить Яндекс метрику в оба таргета.
Для первого добавляется все автоматически. 
![CleanShot 2022-12-06 at 00 54 30@2x](https://user-images.githubusercontent.com/42750568/205750682-cbb007db-7e05-487c-b3b5-1e820b18dab3.png)

для второго таргета нет возможности добавить пакет даже если пытаться добавить в ручную его.

![CleanShot 2022-12-06 at 00 56 00@2x](https://user-images.githubusercontent.com/42750568/205750830-dc90cc1d-c2c1-4b8c-88b5-618e5056b355.png)

**Comment by GLinnik21** [comment]
Здравствуйте!
Да, похоже такая проблема существует и она на стороне Xcode: он почему-то не видит библиотеки, которые были скачаны как `.binaryTarget`. Пока что нашел такой способ решить вашу проблему:
1. Откройте `PSUI.xcodeproj/project.pbxproj` вашего проекта в любом текстовом редакторе.
2. Проматайте файл до секции `/* Begin PBXNativeTarget section */`.
3. Найдите секцию вашего основного таргета `PSUI`.
4. Найдите в этой секции `packageProductDependencies`, он будет выглядеть примерно так: 
```
packageProductDependencies = (
	835ECA0A293F88B000E9035B /* YandexMobileMetrica */,
	835ECA0C293F88B000E9035B /* YandexMobileMetricaCrashes */,
);
```
5. Скопируйте значения c `YandexMobileMetrica` и `YandexMobileMetricaCrashes`.
6. Найдите точно так же секцию вашего второго таргета `PSUI dev`.
7. Если в нем отсутсвует `packageProductDependencies`, то создайте этот ключ. Вставьте туда значения, скопированные в пункте 5, аналогично формату в пункте 4.
