### ISSUE TITLE
How do I pass IDFA availability information to SDK?

### ISSUE THREAD

**Issue by VestaCute** [yandexmobile/metrica-sdk-ios#112]
SDK автоматически получает IDFA? Как передать SDK статус доступности IDFA? 

Реализация получения IDFA:
<img width="579" alt="Снимок экрана 2023-01-13 в 13 13 29" src="https://user-images.githubusercontent.com/46375820/212307282-706579c3-c7c5-4bbc-993b-7f785ae72629.png">

<img width="914" alt="Снимок экрана 2023-01-13 в 13 14 33" src="https://user-images.githubusercontent.com/46375820/212307383-f4cfe729-304f-4300-ae48-19abb9f94c60.png">

**Comment by GLinnik21** [comment]
Здравствуйте. AppMetrica SDK не запрашивает каких-либо разрешений и если у приложения есть доступ к IDFA, то SDK будет использовать его автоматически. Вам не нужно ничего дополнительно передавать.
