### ISSUE TITLE
Ошибка на старте (unrecognized selector)

### ISSUE THREAD

**Issue by kavolorn** [yandexmobile/metrica-sdk-ios#14]
Здравствуйте!

Собираю нативное расширение для Adobe AIR. Стартую метрику следующим кодом:

```objective-c
[YMMYandexMetrica startWithAPIKey:@"0"];
```
и сталкиваюсь с такой проблемой:

```
+[YXPlatformDescription ymm_bundleName]: unrecognized selector sent to class 0xc2faa0
```

Может быть у вас появятся какие-нибудь советы на этот счет?

Спасибо

**Comment by ashender** [comment]
Здравствуйте!
Спасибо за обратную связь.
ymm_bundleName - это метод категории. В бинарном файле библиотеки он есть, если вы запустите
nm libYandexMobileMetrica.a 
то в списке символов поиском можно найти:

libYandexMobileMetrica.a(YXPlatformDescription+YMMAdditions.o):
000000000000006e t +[YXPlatformDescription(YMMAdditions) ymm_buildNumber]
0000000000000098 t +[YXPlatformDescription(YMMAdditions) **ymm_bundleName**]

Следовательно при подключении библиотеки вы забыли указать флаг линкеру, говорящий что необходимо включать в результирующий бинарник ВСЕ методы и категории. Это флаг: **-ObjC**
Его нужно передать в **OTHER_LINKER_FLAGS**

**Comment by yvasileuski** [comment]
Кроме того, хочу обратить внимание, что согласно документации, "Если значение параметра apiKey меньше или равно 0, инициализация библиотеки не будет произведена:
"https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/ios-quickstart-docpage/

**Comment by kavolorn** [comment]
Cегодя провозился много с этим. Сначала думал, что теряю символы - но нет. Оказывается я все корректно делаю - нативное приложение отрабатывает хорошо. А вот линковка в Adobe AIR не срабатывает.

У меня есть воркэраунд, но он работает применительно к исходникам. С бинарником не знаю что сделать. У вас можно попросить кастомную сборку (там нужно добавить не больше 5 строк)?

**Comment by kavolorn** [comment]
У меня была проблема с файлом категории. Я в исходник категорит добавил пустой метод и этот метод вызывал в каком-нибудь значимом месте. И все слинковалось как следует. Не уверен, что в данном случает это поможет.
