### ISSUE TITLE
Время отклика

### ISSUE THREAD

**Issue by kavolorn** [yandexmobile/metrica-sdk-ios#15]
Не могли бы вы рассказать, сколько требует обработки одно событие?

На моих тестах статистика на сервере обновляется в течении от 2 до 25 минут.

**Comment by yvasileuski** [comment]
Ваш вопрос касается клиентской sdk, серверной логики или в целом? Или что-тол конкретное смущает? 
Во многом скорость обновления данных на сайте зависит от того, сколько событий вы посылаете и как долго приложение активно, и на клиенте управляется методами setMaxReportsCount и setDispatchPeriod.

**Comment by kavolorn** [comment]
Смущает, что 25 минут требуется серверу, чтобы опубликовать отчет. Я попробую поэкспериментировать с указанными методами.

Существует ли возможность потерять события при закрытии приложения до срабатывания лимитов?

**Comment by kanstantsin** [comment]
Нет, события хранятся в базе до отправки.
