### ISSUE TITLE
FMDB - Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by ArtemGoryunov** [yandexmobile/metrica-sdk-ios#16]
I got error 
```
[!] Unable to satisfy the following requirements:

- `FMDB (= 2.5)` required by `Podfile.lock`
- `FMDB (~> 2.4)` required by `AWSiOSSDKv2 (2.0.16)`
- `FMDB (= 2.2.0)` required by `YandexMobileMetrica (1.6.2)`
```
My pod file is 
```
platform :ios, '7.0'
pod 'YandexMobileMetrica', '1.6.2'
```

**Comment by yvasileuski** [comment]
Artem, thank you for feedback.
As per initial investigation, YandexMobileMetrica could be used with FMDB 2.5.0 without further action.  Just create your own local podspec for YandexMobileMetrica based on public one where replace FMDB 2.2.0 with 2.5.0.

We will do our best to update dependency in one of nearest releases.
