### ISSUE TITLE
CocoaPods и use_frameworks!

### ISSUE THREAD

**Issue by ItsTipTop** [yandexmobile/metrica-sdk-ios#18]
Если использовать флаг use_frameworks!, который появился недавно в cocoa pods получаю ошибку <code>'YandexMobileMetrica/YandexMobileMetrica.h' file not found</code>.  Если убрать флаг - все окей.
Вот тут подробнее написано про это:
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by igormatyushkin014** [comment]
@ItsTipTop У меня была такая же ошибка. Исправил путем внесения изменений в `YandexMobileMetrica.h`:

```objective-c
#import "YMMYandexMetrica.h"
#import "YMMVersion.h"
```

**Comment by elfenlaid** [comment]
Проверил на YandexMobileMetrica 1.8.5 и cocoapods 0.38.2 - работает.
