### ISSUE TITLE
ERROR: KSSysCtl.c (228)

### ISSUE THREAD

**Issue by alexandrhotko** [yandexmobile/metrica-sdk-ios#21]
KSCrash log error (iOS9 beta):
ERROR: KSSysCtl.c (228): _Bool kssysctl_getProcessInfo(const int, struct kinfo_proc *const): Could not get the name for process 819: Operation not permitted.

P.S. Это критично? Аплик от этого не падает.

**Comment by elfenlaid** [comment]
Нет, это не критично. Подписаться на фикс можно в этом [issue](https://github.com/kstenerud/KSCrash/issues/94).
