### ISSUE TITLE
Bitcode and WatchOS2

### ISSUE THREAD

**Issue by alexandrhotko** [yandexmobile/metrica-sdk-ios#22]
ld: '.../Yandex/metrica-sdk-ios/libYandexMobileMetrica.a(Pods-SetOfLibsIntermediate-YXGCDBasedNetworkLibrary-dummy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

Такая ошибка появляется в проекте c включенным bitcode. Для WatchOS2 необходим bitcode. Если отключить bitcode только в приложении для телефона, то проект нельзя собрать (archive). Проверял на Xcode 7 beta 5, девайсы на iOS9 и WatchOS2.

**Comment by AnarH93** [comment]
Та же самая проблема на свежем релизе xcode 7.0
не билдится ни с enabled bitcode, ни с disabled bitcode

**Comment by dim-bon** [comment]
с disabled bitcode все в порядке )

**Comment by alexandrhotko** [comment]
С disabled bitcode все в порядке до тех пор пока не нужно писать рисширение для часов. Повторюсь, для WatchOS2 необходим bitcode. Если отключить bitcode только в приложении для телефона, то проект нельзя собрать (archive).

**Comment by dim-bon** [comment]
Да, все так про watchOS 2. У нас в проекте Метрика - единственная библиотека, из-за которой мы не можем включить Bitcode. Хотелось бы обновление по-быстрее

**Comment by yvasileuski** [comment]
Я надеюсь, вы в курсе, что с включенным bitcode вы потеряете возможность символизации крешей?

**Comment by alexandrhotko** [comment]
В последней версии Xcode 7.0 (7A220) проблема не проявляется, можно отключить bitcode только в приложении для телефона.

**Comment by yvasileuski** [comment]
Поддержка bitcode появилась в версии 2.1.1. WatchOS2 пока не поддерживается.
