### ISSUE TITLE
Cartage

### ISSUE THREAD

**Issue by alec-c4** [yandexmobile/metrica-sdk-ios#27]
Ребята, привет.
Добавьте пожалуйста поддержку Carthage, для этого достаточно просто включить shared schemes

**Comment by makoni** [comment]
Присоединяюсь

**Comment by bamx23** [comment]
Обнаружил, что достаточно в релизы тут, на Github, положить zip-архив динамического фреймворка.
Последние 2 версии теперь работают с Carthage. Добавьте в `Cartfile`:
```
github "yandexmobile/metrica-sdk-ios" ~> 2.7
```
