### ISSUE TITLE
Test target crash

### ISSUE THREAD

**Issue by Hastewave** [yandexmobile/metrica-sdk-ios#30]
App is crashing while testing
Version - YandexMobileMetrica 2.3.0
How to appropriately handle this behavior?

Logs:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: app_version)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d65ce65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d0d5deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d55a6e2 -[__NSDictionaryM setObject:forKey:] + 1042
	3   AfishaTests                         0x0000000117934162 +[YXStartupParameters platformStartupParametersForProtocolVersion:] + 294
	4   AfishaTests                         0x0000000117933ef2 +[YXStartupParameters startupParametersWithClientIdentifier:protocolVersion:] + 148
	5   AfishaTests                         0x0000000117922dea -[YMMStartupRequest GETParameters] + 78
	6   AfishaTests                         0x0000000117922d54 -[YMMStartupRequest URL] + 30
	7   AfishaTests                         0x00000001178f9213 -[YXRequest buildURLRequest] + 57
	8   AfishaTests                         0x00000001178f8ba4 __44-[YXNetworkRequestController performRequest]_block_invoke + 62
	9   libdispatch.dylib                   0x000000010f9bcd59 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010f9d84a7 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010f9c20e8 _dispatch_queue_drain + 1048
	12  libdispatch.dylib                   0x000000010f9c1aa0 _dispatch_queue_invoke + 595
	13  libdispatch.dylib                   0x000000010f9c33b8 _dispatch_root_queue_drain + 565
	14  libdispatch.dylib                   0x000000010f9c317c _dispatch_worker_thread3 + 98
	15  libsystem_pthread.dylib             0x000000010fd0b68f _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x000000010fd09365 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by yvasileuski** [comment]
Have you set up application version and build number? What values are in CFBundleShortVersionString and CFBundleVersion keys of Info.plist file?

**Comment by yvasileuski** [comment]
If If you talk about unit testing the code, the better way is to stub all 3d party dependencies including Metrika. The reason of described crash is unavailability of main bundle  in tests.

**Comment by Hastewave** [comment]
Yes, I'm talking about unit-testing the code. The problem is that I'm unit-testing AppDelegate but I cannot stub initialize method.
Thanks
