### ISSUE TITLE
Swift integration problems

### ISSUE THREAD

**Issue by moonvader** [yandexmobile/metrica-sdk-ios#34]
i added YandexMobileMetrica.framework to linked frameworks and libraries in Xcode target section

I added
YMMYandexMetrica.activateWithApiKey("my api key") to didFinishLaunchingWithOptions in my AppDelegate file

i get error
+[YXPlatformDescription ymm_bundleName]: unrecognized selector sent to class 0x1055949e8
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[YXPlatformDescription ymm_bundleName]: unrecognized selector sent to class 0x1055949e8'

**Comment by elfenlaid** [comment]
Hi,
I believe the problem could be solved by adding `-ObjC` to Other Linker Flags options in target build settings.
Full integration process described [here](https://tech.yandex.com/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/ios-quickstart-docpage/?ncrnd=9522). Please consider paragraph `If you don't use CocoaPods`. 
Thanks.

**Comment by moonvader** [comment]
if i add -ObjC to Other Linker Flags - i get 50 errors. 
Maybe a company like Yandex can provide step-by-step Swift guide for new developers?

**Comment by yvasileuski** [comment]
Solution to the same issue could be found there https://github.com/yandexmobile/metrica-sample-ios/issues/8

**Comment by yvasileuski** [comment]
Public documentation has been released
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/swift-quickstart-docpage/
