### ISSUE TITLE
The status for the following app has changed to In Rejected.

### ISSUE THREAD

**Issue by evgenijromanishyn** [yandexmobile/metrica-sdk-ios#35]
PLA 3.3.12

We found that your app uses the Advertising Identifier but does not include ad functionality. This does not comply with the terms of the Apple Developer Program License Agreement, as required by the App Store Review Guidelines.

Specifically, section 3.3.12 of the Apple Developer Program License Agreement states:

"You and Your Applications (and any third party with whom you have contracted to serve advertising) may use the Advertising Identifier, and any information obtained through the use of the Advertising Identifier, only for the purpose of serving advertising. If a user resets the Advertising Identifier, then You agree not to combine, correlate, link or otherwise associate, either directly or indirectly, the prior Advertising Identifier and any derived information with the reset Advertising Identifier."

Note: iAd does not use the AdSupport framework, ASIdentifierManager, or the Advertising Identifier. Therefore they are not required for iAd implementations and should not be included in your app for iAd support. 

If your app does not serve ads, please check your code - including any third-party libraries - to remove any instances of:

class: ASIdentifierManager
selector: advertisingIdentifier
framework: AdSupport.framework

If you are planning to incorporate ads in a future version, please remove the Advertising Identifier from your app until you have included ad functionality.

To help locate the Advertising Identifier, use the “nm” tool. For information on the “nm” tool, please see the nm man page. 

If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool lists the methods that the library calls, and "otool -ov" will list the Objective-C class structures and their defined methods. These techniques can help you narrow down where the problematic code resides.

Best regards,
App Store Review

Это не запрещенное API, как уже создавалось выше Issue. Проблема в том, что метрика использует рекламный идентификатор, а саму рекламу в приложении нам не нужно показывать. Но при публикации приложения мы обязаны указать для чего используем рекламный идентификатор. Среди вариантов причин использования нету "для Яндекс метрики". Поэтому Apple и заворачивает все приложения без рекламы и с метрикой. Как известно, с цензорами Apple спорить бесполезно, поэтому люди просто отказываются от метрики Яндекса...

**Comment by yvasileuski** [comment]
Метрика использует idfa например для атрибуции https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-tracking/concepts/policy-docpage/, а не для показов рекламы в приложении. Такое использование разрешено Apple, необходимо лишь это правильно отразить при сабсите приложения в стор. Более подробно можно прочитать например тут: https://help.tune.com/marketing-console/how-to-submit-your-app-when-it-uses-idfa/
