### ISSUE TITLE
Encountered error loading crash report

### ISSUE THREAD

**Issue by evgenijromanishyn** [yandexmobile/metrica-sdk-ios#36]
[PodYandexMobileMetrica_KSCrashReportStore reportWithID:]: Encountered error loading crash report -13D6974B-7C2A-4C6D-9352-34CD9C9D1D05: Error Domain=NSCocoaErrorDomain Code=260

Если приложение хотя бы один раз на чем-то упало - оно больше не открывается. Метрика не может открыть отчет о причине падения и сама заваливает приложение при старте.

[YMMYandexMetrica setReportCrashesEnabled:NO];
[YMMYandexMetrica setLoggingEnabled:NO];

Отключение функций логирования не помогает. Только переустановка приложения.

**Comment by yvasileuski** [comment]
Можно ли привести используемую версию Метрики, пример креша и bundle id для уточнения диагноза?

**Comment by evgenijromanishyn** [comment]
На последней версии не падает. Спасибо за вашу работу :-)
