### ISSUE TITLE
Можно ли идентифицировать откуда пришел пользователь при совершении покупки?

### ISSUE THREAD

**Issue by nullproduction** [yandexmobile/metrica-sdk-ios#39]
Добрый день. У аппметрики есть система трекинговых ссылок и можно узнать откуда пользователь установил приложение, но как идентифицировать пользователя при совершении внутренней покупки? То есть я хочу знать какие рекламные кампании конвертируются в реальные покупки. Я знаю что в последней метрики для ios9 трекинг происходит через вебкит и в метод **YMMYandexMetrica.handleOpenURL** передается url c параметрами, но опять же я знаю какого-то формата url и можно ли из него извлечь какие-то данные для моей цели.

**Comment by dzinad** [comment]
Здравствуйте. С этим вопросом лучше обратиться в саппорт: https://clck.ru/JGnCX или в наш телеграм-чат: https://t.me/appmetrica_chat.
