### ISSUE TITLE
Crashed (SIGSEGV) in ru.yandex.mobile.YandexMobileMetrica.YMMAsyncExecutor.ivarQueue

### ISSUE THREAD

**Issue by Brain89** [yandexmobile/metrica-sdk-ios#43]
Hello, we have received a crash concerning AppMetrica SDK. Here is a log from crashlytics

> 0 libobjc.A.dylib objc_msgSend + 16
> 1 XXX  -[YMMDispatchStrategiesContainer strategies] + 1844348
> 2 XXX -[YMMDispatchStrategiesContainer dispatchMoreIfNeeded] + 1844580
> 3 XXX __69-[YMMYandexMetricaImpl dispatcherDidPerformReport:failed:statusCode:]_block_invoke + 2066384
> 4      libdispatch.dylib  _dispatch_call_block_and_release + 24
> 5 libdispatch.dylib   _dispatch_client_callout + 16
> 6 libdispatch.dylib   _dispatch_queue_drain + 864
> 7 libdispatch.dylib   _dispatch_queue_invoke + 464
> 8 libdispatch.dylib   _dispatch_root_queue_drain + 728
> 9 libdispatch.dylib   _dispatch_worker_thread3 + 112
> 10    libsystem_pthread.dylib _pthread_wqthread + 1092
> 11    libsystem_pthread.dylib start_wqthread + 4

**Comment by dzinad** [comment]
Hello. Please specify AppMetrica SDK version you're using.
