### ISSUE TITLE
Crashed (SIGSEGV): ru.yandex.mobile.YandexNetworkLibrary.YXNetworkRequestController.ivarQueue

### ISSUE THREAD

**Issue by Brain89** [yandexmobile/metrica-sdk-ios#44]
Hello.
We have faced with an issue inside Metrica SDK. Here is log from Crashlytics

> 0      libobjc.A.dylib    objc_release + 20
> 1 libobjc.A.dylib object_cxxDestructFromClass(objc_object_, objc_class_) + 148
> 2 libobjc.A.dylib objc_destructInstance + 92
> 3 libobjc.A.dylib object_dispose + 28
> 4 CoreFoundation  CFRelease + 524
> 5      CoreFoundation -[__NSArrayI dealloc] + 88
> 6 XXX  -[YMMReportEventsBatch .cxx_destruct] + 1946520
> 7      libobjc.A.dylib    object_cxxDestructFromClass(objc_object_, objc_class_) + 148
> 8 libobjc.A.dylib objc_destructInstance + 92
> 9 libobjc.A.dylib object_dispose + 28
> 10    CoreFoundation CFRelease + 524
> 11    CoreFoundation -[__NSArrayI dealloc] + 88
> 12    libobjc.A.dylib object_cxxDestructFromClass(objc_object_, objc_class_) + 148
> 13    libobjc.A.dylib objc_destructInstance + 92
> 14    libobjc.A.dylib object_dispose + 28
> 15    XXX -[YXNetworkRequestController .cxx_destruct] + 2089616
> 16    libobjc.A.dylib object_cxxDestructFromClass(objc_object_, objc_class_) + 148
> 17    libobjc.A.dylib objc_destructInstance + 92
> 18    libobjc.A.dylib object_dispose + 28
> 19    XXX  -[YXNetworkRequestController dealloc] + 2088196
> 20    libsystem_blocks.dylib  _Block_release + 256
> 21    libdispatch.dylib   _dispatch_client_callout + 16
> 22    libdispatch.dylib   _dispatch_queue_drain + 1448
> 23    libdispatch.dylib   _dispatch_queue_invoke + 132
> 24    libdispatch.dylib   _dispatch_root_queue_drain + 720
> 25    libdispatch.dylib   _dispatch_worker_thread3 + 108
> 26    libsystem_pthread.dylib _pthread_wqthread + 816
> 27    libsystem_pthread.dylib start_wqthread + 4

**Comment by BamX** [comment]
Could you please provide more information about this crash (like public Crashlytics crash link) to email bamx23@yandex-team.ru ?

**Comment by dzinad** [comment]
Hello. Please specify AppMetrica SDK version you're using.
