### ISSUE TITLE
Crashed (SIGABRT): ru.yandex.mobile.YandexMobileMetrica.YMMAsyncExecutor.ivarQueue

### ISSUE THREAD

**Issue by Brain89** [yandexmobile/metrica-sdk-ios#45]
Hello,
We have faced with a new one issue in AppMetrica SDK. Here is a crash log from Crashlytics.

> 0 libsystem_kernel.dylib  syscall_thread_switch + 8
> 1 libsystem_platform.dylib    _os_lock_handoff_lock_slow + 78
> 2 libsystem_malloc.dylib  szone_malloc_should_clear + 60
> 3 libsystem_malloc.dylib  malloc_zone_malloc + 88
> 4 libsystem_malloc.dylib  malloc + 46
> 5 libsystem_blocks.dylib  _Block_copy_internal + 230
> 6 libdispatch.dylib   _dispatch_Block_copy + 48
> 7 libdispatch.dylib dispatch_async + 58
> 8 XXX -[YMMAsyncExecutor execute:] + 5600617
> 9 XXX -[YMMDispatcher execute:] + 5568427
> 10 XXX     -[YMMDispatcher performReport:] + 5569043
> 11 XXX    __63-[YMMYandexMetricaImpl dispatchStrategyWantsReportingToHappen:]_block_invoke + 5775903
> 12 libdispatch.dylib _dispatch_call_block_and_release + 10
> 13 libdispatch.dylib _dispatch_queue_drain + 1762
> 14 libdispatch.dylib _dispatch_queue_invoke + 282
> 15 libdispatch.dylib  _dispatch_root_queue_drain + 400
> 16 libdispatch.dylib  _dispatch_worker_thread3 + 94
> 17 libsystem_pthread.dylib    _pthread_wqthread + 1024
> 18 libsystem_pthread.dylib     start_wqthread + 8

**Comment by dzinad** [comment]
Hello. Please specify AppMetrica SDK version you're using.
