### ISSUE TITLE
Как использовать аппметрику в другой cocaopods зависимости?

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#48]
Хочу сделать обертку над аппметрикой и вынести ее в cocapods зависимость.

Спецификация выглядит так:

```
Pod::Spec.new do |s|
  s.name = 'Flint'
  s.version = '0.1'
  s.source = { :git => 'https://nullproduction@bitbucket.org/nullproduction/flint.git', :tag => s.version }
  s.ios.deployment_target = '8.0'
  s.source_files = 'Source/**/*.{c,h,m,swift}'
  s.dependency 'SQLCipher'
  s.dependency 'YandexMobileMetrica', '2.5.1'
  s.public_header_files = 'Source/Flint.h'
end
```

При команде pod install получаю такю ошибку:

`The 'Pods-FlintDemo' target has transitive dependencies that include static binaries: (/Users/mezhevikin/Desktop/Projects/FlintDemo/Pods/YandexMobileMetrica/YandexMobileMetrica.framework`

**Comment by bamx23** [comment]
Такая проблема возникает при использовании с `use_frameworks!` и существует у всех pod'ов со статическими библиотеками внутри. В ближайшее время планируется наладить поставку SDK AppMetrica в виде динамического фреймворка, что решит данную проблему.

**Comment by mezhevikin** [comment]
@bamx23 Спасибо за ответ. Было бы здорово если бы такая возможность появилась.
Так как я иcпользую swift, без use_frameworks! тоже не работает:

`Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: Flint`
