### ISSUE TITLE
Предупреждения при компиляции на swift3 + xcode8

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#50]
Использую 'YandexMobileMetrica/Dynamic', '2.6.0'

Получаю два предупреждения:
`
/Users/mezhevikin/Desktop/Projects/Analitics/Example/Pods/YandexMobileMetrica/dynamic/YandexMobileMetrica.framework/Headers/YMMYandexMetricaConfiguration.h:30:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
`

`
/Users/mezhevikin/Desktop/Projects/Analitics/Example/Pods/YandexMobileMetrica/dynamic/YandexMobileMetrica.framework/Headers/YMMYandexMetricaPreloadInfo.h:18:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
`

На функциональностью не влиет, но считаю нужным сообщить

**Comment by bamx23** [comment]
Исправили в 2.6.5
