### ISSUE TITLE
Динамический фреймворк не дает опубликовать приложение

### ISSUE THREAD

**Issue by kotvaska** [yandexmobile/metrica-sdk-ios#53]
При попытке опубликовать приложение с подключенной метрикой выдает ошибки:

ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle taxicomplex-ios-client.app/Frameworks/YandexMobileMetrica.framework is invalid. The minimum value is 8.0"
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

В настройках проекта нигде ниже 8.0 не используем, в Podfile тоже.
Подключаем фреймворк с помощью хука, описанного в #52 . Можете подсказать, что может быть причиной?

**Comment by mezhevikin** [comment]
@kotvaska Podfile покажите

**Comment by kotvaska** [comment]
@mezhevikin он выглядит так:

source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'
use_frameworks!

target 'taxicomplex-ios-client' do
    pod 'CrittercismSDK'
    pod 'SWRevealViewController'
    pod 'Spring', :git=> 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
    pod 'HanekeSwift'
    pod 'AFNetworking', '1.3.3'
    pod 'SwiftyJSON', '2.4.0'
    pod 'HMSegmentedControl'
    pod 'TSMessages'
    pod 'Alamofire'
    pod 'CardIO'
    pod 'YandexMobileMetrica/Dynamic'

end

post_install do |installer|
    appmetricaPlistPath = "Pods/YandexMobileMetrica/dynamic/YandexMobileMetrica.framework/Info.plist"
    appmetricaVersion = `/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' #{appmetricaPlistPath}`.strip
    if ['2.6.0', '2.6.1', '2.6.2'].include? appmetricaVersion
        system("/usr/libexec/PlistBuddy -c 'Set :CFBundleIdentifier org.cocoapods.YandexMobileMetrica' #{appmetricaPlistPath}")
        system("plutil -convert binary1 #{appmetricaPlistPath}")
        else
        puts("Please, remove workaround for AppMetrica dynamic framework.")
    end
end

**Comment by mezhevikin** [comment]
@kotvaska Дождемся официального ответа, я сам пока не пробовал выкладывать с билд с динамической аппметрикой. Подфайл у вас правильный.

Так же можете попробовать использовать статическую библиотеку, для этого замените pod 'YandexMobileMetrica/Dynamic' на pod 'YandexMobileMetrica'. Вам вроде некретично какую версию использовать

**Comment by kotvaska** [comment]
@mezhevikin попробую со статической. В описании библиотеки рекомендации были к динамической, вот и решили с ней :)

**Comment by mezhevikin** [comment]
@kotvaska Все правильно. От статических фреймверков нужно отказываться, но если нужно срочно выложить в стор, то стоит попробовать.

**Comment by bamx23** [comment]
Добрый вечер! @mezhevikin спасибо за помощь!
Данную проблему также решим в рамках следующего релиза. Сейчас же стоит использовать такой workaround:

```ruby
post_install do |installer|
    appmetricaPlistPath = "Pods/YandexMobileMetrica/dynamic/YandexMobileMetrica.framework/Info.plist"
    appmetricaVersion = `/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' #{appmetricaPlistPath}`.strip
    if ['2.6.0', '2.6.1', '2.6.2'].include? appmetricaVersion
        system("/usr/libexec/PlistBuddy -c 'Set :CFBundleIdentifier org.cocoapods.YandexMobileMetrica' #{appmetricaPlistPath}")
        system("/usr/libexec/PlistBuddy -c 'Set :MinimumOSVersion 8.0' #{appmetricaPlistPath}")
        system("plutil -convert binary1 #{appmetricaPlistPath}")
    else
        puts("Please, remove workaround for AppMetrica dynamic framework.")
    end
end
```

**Comment by kotvaska** [comment]
@bamx23 спасибо, это работает хорошо. ждем обновление :)

**Comment by bamx23** [comment]
@kotvaska проблема с ITMS-90125 также решилась?

**Comment by bamx23** [comment]
Выпустили 2.6.5, обновитесь. Эти проблемы там решены.

**Comment by kotvaska** [comment]
@bamx23, да, эта проблема тоже решилась.

спасибо! обновимся обязательно:)
