### ISSUE TITLE
YandexMobileMetrica and Swift 3.1 project 

### ISSUE THREAD

**Issue by YurchukV** [yandexmobile/metrica-sdk-ios#57]
Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/swift-quickstart-docpage/

**Comment by alekzuz** [comment]
Still not fixed ?

**Comment by bamx23** [comment]
Documentation is still not fixed. But we recommend AppMetrica activation in `applicationDidFinishLaunching` method.

**Comment by aleksey-ho** [comment]
any updates? still not fixed in ios-extension-quickstart
https://appmetrica.yandex.ru/docs/mobile-sdk-dg/tasks/ios-extension-quickstart.html

**Comment by GLinnik21** [comment]
Well, there is no `applicationDidFinishLaunching` method for App Extensions. In your opinion, how should we fix this documentation?
