### ISSUE TITLE
Crash (SIGABRT)

### ISSUE THREAD

**Issue by artuska** [yandexmobile/metrica-sdk-ios#68]
В файле YMMAppMetricaPlugin.m на 178 строчке:

```
if (customAppVersion != nil) {
    configuration.customAppVersion = customAppVersion; // тут SIGABRT
}
```

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x1030f0f50'

**Comment by bamx23** [comment]
Речь о Cordova, насколько я понял. Задачи лучше открывать в соответствующем репозитории:
https://github.com/yandexmobile/metrica-plugin-cordova.
Проверьте, что в `appVersion` конфигурации активации на стороне JS передается строка.

**Comment by artuska** [comment]
Ок, думал, проблема именно в SDK. Ужасно извиняюсь, действительно, по-невнимательности передаю не то, что нужно.

**Comment by bamx23** [comment]
Ничего страшного. Особенности ObjC, что можно любой объект в любую переменную/свойство записать. SDK такого действительно не ожидает, поэтому и падает сразу.
