### ISSUE TITLE
Apple Watch?

### ISSUE THREAD

**Issue by gerchicov-bp** [yandexmobile/metrica-sdk-ios#69]
https://tech.yandex.ru/appmetrica/doc/mobile-sdk-dg/tasks/ios-quickstart-docpage/
`iOS Watch версии 1.x (beta)`
пытаюсь установить через cocoapods - не может, потому что "pod не поддерживает watchos"
попробовал готовым фреймворком - требует библиотеки, которых нет в watchos

**Comment by bamx23** [comment]
Будем разбираться, спасибо

**Comment by ybraman** [comment]
Пока поддержка watchOS отсутствует. Возможно, скоро появится.
