### ISSUE TITLE
Крэш аппметрики

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#71]
Привет. В Аппметрики наблюдаю крэш моего приложение в ios 11.4 из-за sdk аппметрики. Падает ее тред.

Вот полный крешлог - https://gist.github.com/mezhevikin/69a09b1e6b2a59d73c029a537b790fa0

Thread 2 Crashed:
0   YandexMobileMetrica             0x0000000100bf9774 0x100b30000 + 825204 (PodYandexMobileMetrica_ksthread_getQueueName + 128)
1   YandexMobileMetrica             0x0000000100bf975c 0x100b30000 + 825180 (PodYandexMobileMetrica_ksthread_getQueueName + 104)
2   YandexMobileMetrica             0x0000000100be2478 0x100b30000 + 730232 (PodYandexMobileMetrica_ksccd_init + 488)
3   libsystem_pthread.dylib         0x0000000184ed9220 0x184ed7000 + 8736 (<redacted> + 272)
4   libsystem_pthread.dylib         0x0000000184ed9110 0x184ed7000 + 8464 (_pthread_start + 292)

**Comment by bamx23** [comment]
День добрый! Проблема была исправлена в версии 3.0.1. Последняя версия 3.1.1, рекомендуем сразу обновиться на неё.

**Comment by mezhevikin** [comment]
@bamx23 спасибо
