### ISSUE TITLE
Добавляется лишний UITabBarItem в UITabViewController

### ISSUE THREAD

**Issue by lynx56** [yandexmobile/metrica-sdk-ios#73]
iphone X, iOS 11.4.1, metrica sdk последняя версия.

Есть кастомный UITabViewController (главный контроллер приложения), после инициализации аппметрики (YMMYandexMetrica.activate), появляется дополнительный контроллер ( c childcontroller SFSafariViewController) во viewControllers, из-за этого появляется лишний пустой tab, после динамической вставки и апдейта моего таба self.viewControllers.insert
С выключенной аппметрикой всё работает должным образом. Можете подсказать что с этим можно сделать?
![img_8184](https://user-images.githubusercontent.com/6124986/46173345-a26dc100-c2ae-11e8-96b9-970ebbdae84f.PNG)
с выключенной метрикой
![img_8185](https://user-images.githubusercontent.com/6124986/46173349-a699de80-c2ae-11e8-9814-89351cd3501c.PNG)

**Comment by bamx23** [comment]
Добрый вечер! О проблеме знаем и исправим в следующем релизе.

**Comment by bamx23** [comment]
Косвенно повлияет на качество аттрибуции, но в целом можно удалить как временное решение.

**Comment by bamx23** [comment]
Добрый день! В 3.4.0 исправили данную проблему.
