### ISSUE TITLE
Размер SDK

### ISSUE THREAD

**Issue by ggudimenko** [yandexmobile/metrica-sdk-ios#74]
Почему размер AppMetrica SDK для iOS такой большой? Есть ли возможность его как-то уменшить?
На скрине видно, что размер SDK 42 Mb.
![image](https://user-images.githubusercontent.com/33896821/46214347-612fec80-c354-11e8-82d8-772f451ac1f9.png)

**Comment by bamx23** [comment]
Добрый день!
Да, о проблеме размера SDK мы знаем и ищем способы уменьшить.
Речь идет о динамическом фреймворке?

**Comment by bamx23** [comment]
День добрый! В 3.4.0 удалось серьезно сократить размер динамического SDK (до 25.3 Мб у ядра + 6.5 Мб у крэш-хэндлера)

**Comment by ggudimenko** [comment]
> День добрый! В 3.4.0 удалось серьезно сократить размер динамического SDK (до 25.3 Мб у ядра + 6.5 Мб у крэш-хэндлера)

Да, речь шла о динамическом фрэймворке. Спасибо за информацию, буду использовать.
