### ISSUE TITLE
👻 Странный баг c "призрачным SFSafariViewController"

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#75]
Есть ios приложение на swfit в котором одна единственная зависимость - аппметрика. 
Переодически при открытии приложения перестает работать tap события на главном экране, при этом виднеется полупрозрачный SFSafariViewController.

1. Дело в том что мое приложение не использует  SFSafariViewController нигде.
2. В приложении нет других зависимостей кроме аппметрики.
3. Баг очень трудновоспроизводимый. Появляется 1 раз из 1000. Только на реальных устройствах. Не разу не удалось воспроизвести с подключенным xcode в режиме debug. 

 **Техданные:**
1. id приложения 870507
2. язык swift
3. pod зависимость YandexMobileMetrica/Dynamic 3.3.0
4. баг наблюдается на ios10 - 11

Скриншот - 
![Image of Yaktocat](https://i.imgur.com/a8qw8g0.png)

**Comment by bamx23** [comment]
Добрый день! О проблеме знаем и исправим в следующем релизе(через 1-2 недели).

**Comment by mezhevikin** [comment]
@bamx23  Добрый день. 3.4.0 не исправляет этот баг?

**Comment by bamx23** [comment]
День добрый! Да, в 3.4.0 этот баг исправили.

**Comment by mezhevikin** [comment]
@bamx23 в 3.4.1 наблюдая этот баг опять. проблема не исправили!

**Comment by bamx23** [comment]
Спасибо за наблюдение, поставили задачей на ближайший релиз

**Comment by mezhevikin** [comment]
@bamx23 Добрый день. Есть ли какие-то новости по багу?

**Comment by bamx23** [comment]
Функциональность, приводящая к такому поведению, будет отключена со стороны сервера в ближайшее время. К сожалению, не могу дать более точные сроки.

**Comment by mezhevikin** [comment]
@bamx23 А куда и  как аппметрка добавляет SFSafariViewController? 
Хочу попробовать сделать временное решение проблемы.
У меня было предположение что в rootViewController через метод addChildViewController.
Я пробовал его переопределять и делать проверку не является ли добавляемый контроллер SFSafariViewController, но похоже это не работает.

**Comment by bamx23** [comment]
Добавление происходит так, как Вы говорите, но добавляется не SFSafariViewController, а UIViewController с SFSafariViewController внутри.
Однако всё же рекомендую дождаться правки с нашей стороны. Постараюсь форсировать его.

**Comment by mezhevikin** [comment]
@bamx23 Хорошо. Спасибо, буду ждать. Хорошего дня 👍

**Comment by bamx23** [comment]
Функционал отключен, проблема больше не должна проявляться.

**Comment by mezhevikin** [comment]
@bamx23 Спасибо! Круто! Будем наблюдать :)
