### ISSUE TITLE
No such module 'YandexMobileMetrica'

### ISSUE THREAD

**Issue by OneSman7** [yandexmobile/metrica-sdk-ios#76]
Using latest (3.4.0) static framework with swift and Cocoapods.
Project do not compile with error above on` import YandexMobileMetrica`.

**Comment by bamx23** [comment]
Thank you!
Module map is missing in 3.4.0. Will be fixed ASAP.

**Comment by bamx23** [comment]
Release 3.4.1 with a fix is out
