### ISSUE TITLE
Ошибка компиляции в XCode 10

### ISSUE THREAD

**Issue by 1MaXimus** [yandexmobile/metrica-sdk-ios#78]
В XCode 10 компилируется с ошибкой:
**library not found for -lstdc++.6**

Когда будет готов релиз для XCode 10 и iOs 12+?

**Comment by bamx23** [comment]
Последние несколько релизов собирались Xcode 8.2.1 с целью обратной совместимости.
Релиз 3.5.0, который мы планируем выпустить в конце этой/начале следующей недели, будет собран Xcode 10.1.
Подскажите, какая сабспека `YandexMobileMetrica` используется?

**Comment by 1MaXimus** [comment]
Что такое сабспека?

**Comment by bamx23** [comment]
В CocoaPods при добавлении зависимости можно указать конкретный вариант библиотеки: `subspec`. Выглядит это так: в Podfile прописывается `pod "YandexMobileMetrica/Static/Core", "3.4.1"`, где `Static/Core` - сабспека.
Подробнее тут можно почитать: https://guides.cocoapods.org/syntax/podspec.html#subspec
У АппМетрики есть несколько сабспек: `Static`, `Static/Core`, `Static/Crashes`, `Dynamic`, `Dynamic/Core`, `Dynamic/Crashes`. По умолчанию, если ничего не указывать будет использоваться `Static`, который транзитивно затянет `Static/Core` и `Static/Crashes`.

**Comment by 1MaXimus** [comment]
Сначала использовали версию 2.9.8, потом 3.4.1

**Comment by 1MaXimus** [comment]
О, последнее - наш вариант.

**Comment by bamx23** [comment]
Тогда немного странно, т.к. при статической сборке такая ошибка была бы только если `stdc++` был прописан у нас в [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/4/e/1/YandexMobileMetrica/3.4.1/YandexMobileMetrica.podspec.json#L18). Проверьте, может быть какая-то другая зависимость требует `libstdc++`.

**Comment by 1MaXimus** [comment]
В 9 XCode с библиотеками libstdc++.* Отлично все работает. В 10 их нет.

**Comment by bamx23** [comment]
Да, это правда. Но АппМетрика не зависит от `libsdtc++`.

**Comment by 1MaXimus** [comment]
Получается, что зависит. И карты тоже.

**Comment by 1MaXimus** [comment]
"std::locale::~locale()", referenced from:
      UrlBuilder::UrlBuilder(std::string const&) in libYandexMapKit.a(UrlBuilder.o)
      GeoSearch::(anonymous namespace)::parseTime(std::string const&, tm&) in libYandexMapKit.a(GeoSearchParser.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Это последние строки из лога при отключенной библиотеке -l"stdc++.6" в "Other Linker Flags"
Для метрики то же самое получается.

**Comment by bamx23** [comment]
А можно для АппМетрики такой лог увидеть? Потому что покачто видно. что проблема в YandexMapKit, который зависит от [libstdc++](https://github.com/CocoaPods/Specs/blob/master/Specs/5/7/2/YandexRuntime/3.2.0/YandexRuntime.podspec.json#L31).

**Comment by bamx23** [comment]
Связался с разработчиками YandexMapKit. Они запланировали исправление на ближайший релиз. Можете создать issue у них, чтобы следить за прогрессом: https://github.com/yandex/mapkit-ios-demo/issues

**Comment by bamx23** [comment]
Обязательно перепроверю. 
На всякий случай уточню, что АппМетрика зависит от `libc++`, которая в Xcode 10 присутствует. Может быть похожий лог был с ней.

**Comment by 1MaXimus** [comment]
История такая. Начал компилировать проект с АппМетрикой и картами. 
Ошибка **library not found for -lstdc++.6**.
Убрал -lstdc++.6 из "Other Linker Flags".
Ошибка **ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)** с метрикой.
Исключил метрику из Podfile.
Ошибка **ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)** но уже с картами.
Установил XCode 9.4
Компиляция без ошибок.
Перетялул три библиотеки **libstdc++.6.0.9.tbd, libstdc++.6.tbd и libstdc++.tbd** (на всякий случай три) из 9 в 10 XCode.
Снова добавил метрику в Podfile.
Все скомпилировалось.

**Comment by 1MaXimus** [comment]
Примерно когда ждать для 10 XCode релиз?

**Comment by bamx23** [comment]
Релиз 3.5.0 планируется на этой неделе.
Однако я ещё раз проверил и чистый проект с подключенной `YandexMobileMetrica 3.4.1` собирается в `Xcode 10.1 (10B61)` без ошибок. По логу видно, что никакой `stdc++` не затягивается. Прошу Вас ещё раз проверить интеграцию.

**Comment by bamx23** [comment]
Версия 3.5.0 вышла в релиз. Никаких проблем при сборке в Xcode 10.1 не выявлено.
