### ISSUE TITLE
Missed armv7s since 3.5.0?

### ISSUE THREAD

**Issue by VitaliyPykhtin** [yandexmobile/metrica-sdk-ios#80]
с релиза 3.5.0 пропала armv7s, верните пожалуйста.

arm64e планируется включить так же в новые релизы?

**Comment by bamx23** [comment]
Мы постараемся включить armv7s обратно, а также изучить возможность включения arm64e.
Можете рассказать, какая есть необходимость этих архитектур у вас?

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день! AppMetrica
