### ISSUE TITLE
Apple Store Connect Operation Error

### ISSUE THREAD

**Issue by vitys96** [yandexmobile/metrica-sdk-ios#81]
Добрый вечер, возникает такая проблема при выгрузки приложения в appStore. Используется xCode 11. Версия метрики 3.8.0

![2019-09-26 20 57 38](https://user-images.githubusercontent.com/36761441/65712779-755e1500-e0a0-11e9-8b30-20991e248d41.jpg)

**Comment by bamx23** [comment]
Добрый вечер, спасибо за обращение. В ближайшее время исправим, а пока что можете использовать версию SDK 3.7.1.

**Comment by vitys96** [comment]
Не подскажете как ее использовать?)

Отправлено с iPhone

**Comment by bamx23** [comment]
Немного уточню. Если есть возможность использовать статическую версию библиотеки, то в ней такой проблемы не будет.
Если вы интегрируетесь через CocoaPods, то для использования версии 3.7.1 надо указать следующую строчку в Podfile:
`pod "YandexMobileMetrica", "3.7.1"`

**Comment by vitys96** [comment]
Возникает ошибка в консоли:


[!] CocoaPods could not find compatible versions for pod "YandexMobileMetricaPush/Dynamic":
   In Podfile:
     YandexMobileMetricaPush/Dynamic (= 3.7.1)
 
None of your spec sources contain a spec satisfying the dependency: `YandexMobileMetricaPush/Dynamic (= 3.7.1)`.
 
You have either:
  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
  * mistyped the name or version.
  * not added the source repo that hosts the Podspec to your Podfile.
 
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default. 
>Четверг, 26 сентября 2019, 23:01 +03:00 от Nikolay Volosatov <notifications@github.com>:
>
>Немного уточню. Если есть возможность использовать статическую версию библиотеки, то в ней такой проблемы не будет.
>Если вы интегрируетесь через CocoaPods, то для использования версии 3.7.1 надо указать следующую строчку в Podfile:
>pod "YandexMobileMetrica", "3.7.1"
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

_____________________________
С уважением, Виталий Охрименко

**Comment by bamx23** [comment]
YandexMobileMetricaPush нужно оставить как есть, там последняя актуальная версия "0.8.0"

**Comment by bamx23** [comment]
Исправлено в 3.8.1, можно обновляться
