### ISSUE TITLE
Add Swift Package Manager.

### ISSUE THREAD

**Issue by diss1993** [yandexmobile/metrica-sdk-ios#83]
Хотел бы узнать, о возможности добавления AppMetrica через SPM?

**Comment by bamx23** [comment]
Добрый день! Также обсуждалось в рамках #82 
На данный момент поддержка бинарных зависимостей в SPM не до конца реализована, но как только она появится, мы добавим поддержку со своей стороны.

**Comment by wacumov** [comment]
Hi! Now SwiftPM supports binary dependencies, could you please build the framework as an `.xcframework` file? 
Then you can just add `Package.swift` file with the following content - 
```swift
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "YandexMobileMetrica",
    products: [
        .library(
            name: "YandexMobileMetrica",
            targets: ["YandexMobileMetrica"]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(name: "YandexMobileMetrica",
                      url: "https://github.com/yandexmobile/metrica-sdk-ios/releases/download/3.12/YandexMobileMetrica.xcframework.zip",
                      checksum: "THE_CHECKSUM")
    ]
)
```

**Comment by maksymbiriukov** [comment]
Добрый день, также присоединюсь к предыдущему комментарию, SwiftPM уже поддерживает binary dependencies, было бы круто увидеть релиз с этой фичей.

**Comment by DSanzh** [comment]
Добрый день, аналогично. SPM must have

**Comment by dzinad** [comment]
Поддержка SPM запланирована и войдет в один из ближайших релизов.

**Comment by GLinnik21** [comment]
SPM был добавлен в [последнем релизе](https://github.com/yandexmobile/metrica-sdk-ios/releases/tag/3.14.0)

**Comment by diss1993** [comment]
Вот это подарок под НГ!
