### ISSUE TITLE
Catalyst

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#84]
Добрый день. Планируется ли поддержка catalyst в будущем?

Сейчас вот такая ошибка:
` in Pods/YandexMobileMetrica/static/YandexMobileMetrica.framework/YandexMobileMetrica(YMMUserProfileUpdatesProcessor.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file 'Pods/YandexMobileMetrica/static/YandexMobileMetrica.framework/YandexMobileMetrica' for architecture x86_64`

**Comment by bamx23** [comment]
Добрый!
Поддержка Catalyst запланирована, но о сроках ничего подсказать не смогу. Следите за обновлениями тут или в блоге.

**Comment by mezhevikin** [comment]
@bamx23 спасибо за ответ

**Comment by svanichkin** [comment]
Ребята, Catalyst уже повсеместно, пора бы добавить поддержку...

**Comment by mezhevikin** [comment]
@bamx23 Привет. Есть какие-то новости про Catalyst? Не в коем случае не пытаюсь торопить, просто любопытно и хотелось бы немного узнать внутренней кухни.

1. Портирование больших фреймверков таких как АппМетрика это вообще реально?
2. Рассматривали ли возможность сделать отдельную зависимость, которая для iOS работает как обычная АппМетрика, а для Catalyst просто как заглушка. Это не решение проблемы, но можно было бы просто подключить такую зависимость и не писать вечные обертки:

```
#if !targetEnvironment(macCatalyst)
import MobileAppMetrica
#endif

```

**Comment by quazarteam** [comment]
Добрый день,

на дворе ноябрь - где поддержка Catalyst? когда вообще планируется?

**Comment by alxrguz** [comment]
Присоединяюсь к теме, Catalyst и SPM тоже очень ждем :)

**Comment by AppMetricaOvermindGenius180iq** [comment]
Указанное предложение было заведено в [нашем специализированном сервисе](https://vote.appmetrica.yandex/en/communities/4/topics/185-podderzhka-catalyst) . Приглашаем вас подписаться на него и проголосовать за него.

**Comment by mezhevikin** [comment]
@AppMetricaOvermindGenius180iq Зачем закрывать issue если проблема не была решена?

**Comment by AppMetricaOvermindGenius180iq** [comment]
Здесь все же скорее место для вопросов или жалоб, а это - продуктовый запрос на доработку. Для этого у нас отдельный сервис. В нем тоже есть оповещения.
