### ISSUE TITLE
Различаются значения AppMetrica и Play console/App Store Connect аналитика

### ISSUE THREAD

**Issue by Levin228** [yandexmobile/metrica-sdk-ios#88]
Здравствуйте, возникла проблема с установками приложения, в AppMetrica значений намного больше чем в Play console или App Store Connect, подскажите пожалуйста какие параметры включаются в метрику, от которых значения установок больше.
Заранее спасибо

**Comment by alexklints** [comment]
Здравствуйте. 

Расследование проблемы потребует знания чувствительных данных вроде API_KEY. Напишите, пожалуйста, в нашу поддержку.

**Comment by Levin228** [comment]
> Здравствуйте.
> 
> Расследование проблемы потребует знания чувствительных данных вроде API_KEY. Напишите, пожалуйста, в нашу поддержку.

Вы можете подсказать по каким параметрам в метрику летит событие об установке приложения?

**Comment by alexklints** [comment]
Я не совсем понял ваш вопрос. Событие установки формируется с началом первой пользовательской сессии приложения. Установки могут различаться, например, если у вас на один API_KEY атрибутировано несколько приложений или часть установок было из сторонних источников.

**Comment by Levin228** [comment]
> Я не совсем понял ваш вопрос. Событие установки формируется с началом первой пользовательской сессии приложения. Установки могут различаться, например, если у вас на один API_KEY атрибутировано несколько приложений или часть установок было из сторонних источников.

Спасибо, и еще один маленький вопрос, у нас используется один API_KEY для android и ios
Может быть такое что они как то пересекаются из-за одного ключа? И вообще может быть лучше использовать два ключа, отдельно android и отдельно ios?

**Comment by alexklints** [comment]
> Спасибо, и еще один маленький вопрос, у нас используется один API_KEY для android и ios
Может быть такое что они как то пересекаются из-за одного ключа? И вообще может быть лучше использовать два ключа, отдельно android и отдельно ios?

Нет. Сегментация по платформе позволит увидеть данные об установках только с одной платформы. В использовании отдельных ключей нет никакой необходимости.

**Comment by Levin228** [comment]
> > Спасибо, и еще один маленький вопрос, у нас используется один API_KEY для android и ios
> > Может быть такое что они как то пересекаются из-за одного ключа? И вообще может быть лучше использовать два ключа, отдельно android и отдельно ios?
> 
> Нет. Сегментация по платформе позволит увидеть данные об установках только с одной платформы. В использовании отдельных ключей нет никакой необходимости.

Проблема в том, что данные в отчете User Acquisition за одно и то же время и за одну и ту же версию приложения (если брать какую-то определенную платформу, например android) разнятся с данными из магазинов в несколько тысяч
У вас есть идеи в чем может быть проблема?
