### ISSUE TITLE
Проблемы с указанием Метрики, как зависимости в Cocoapods.

### ISSUE THREAD

**Issue by AlexGerm** [yandexmobile/metrica-sdk-ios#89]
Добрый день! У меня есть фреймворк, который распространяется через Cocoapods. 
В качестве зависимости в podspec-файле указана последняя версия метрики:
`spec.dependency "YandexMobileMetrica/Dynamic", "3.12.0"`

При отправке podspec'а в репозиторий со спеками возникает такая проблема, ну и podspec невозможно запушить из-за этого.
```
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, 
but the range of supported deployment target versions is 9.0 to 14.0.99. 
(in target 'YandexMobileMetrica' from project 'Pods')
```
Не планируется ли обновление минимальной версии ios до 9.0?

**Comment by GLinnik21** [comment]
Здравствуйте. 
Да, действительно такая проблема присутствует на Xcode 12. Пока что могу предложить использовать для заливки более старую версию Xcode через `xcode-select` или же разрешить ворнинги через `pod trunk push --allow-warnings`.
Поднятие минимальной версии сейчас рассматривается.

**Comment by AlexGerm** [comment]
Спасибо за оперативный ответ!

**Comment by GLinnik21** [comment]
С релиза 3.14.0 отключили поддержку iOS 8, поэтому больше таких проблем возникать не должно
