### ISSUE TITLE
После добавление SPM пакета AppMetrica

### ISSUE THREAD

**Issue by diss1993** [yandexmobile/metrica-sdk-ios#90]
Добрый день.
После добавления SPM пакета яндекс Метрики.
Возникли сложности при загрузки приложения в AppStore Connect.
Сами ошибки на скриншоте:
![Снимок экрана 2020-12-30 в 00](https://user-images.githubusercontent.com/4978817/103305609-c728e400-4a35-11eb-9415-08c995ab1da9.jpg)

**Comment by GLinnik21** [comment]
Здравствуйте. Судя по всему SPM сам кладет библиотеки в несколько мест (Plugins и Frameworks). Кажется, с нашей стороны, конфигом пакета мы на это никак повлиять не можем. У нас внутри другие команды сталкивались с такой проблемой и решили её скриптом в билд фазах.
