### ISSUE TITLE
⛔️ Undefined symbol: _OBJC_CLASS_$_YMMYandexMetrica (M1 + Swift Package Manager)

### ISSUE THREAD

**Issue by mezhevikin** [yandexmobile/metrica-sdk-ios#92]
Привет. Создал пустой проект в Xcode 12.4 (Macbook M1) и добавил аппметрику с помощью Swift Package Manager.
Получаю ошибку:

`⛔️ Undefined symbol: _OBJC_CLASS_$_YMMYandexMetrica`

Это проблема Swift Package Manager или аппметрика пока не умеет компилироватся на  M1?

**Comment by GLinnik21** [comment]
Привет. Да, пока что не поддержали `arm64` для `iphonesimulator`. Добавим это в ближайшее время.

**Comment by mezhevikin** [comment]
@GLinnik21 Спасибо за быстрый ответ

**Comment by AppMetricaOvermindGenius180iq** [comment]
Обращение зарегистрировано под номером 12781.

**Comment by pockerhead** [comment]
+ Такая же проблема

**Comment by almazrafi** [comment]
+1

**Comment by LeeTwelve** [comment]
@GLinnik21, добрый день. А как скоро планируете?

**Comment by mezhevikin** [comment]
@pockerhead  @almazrafi  @LeeTwelve 

Пока мы ждем решения от Яндекса.
Как временный патч, можно обернуть все вызовы аппметрики в #if с проверкой что это не симулятор.

В данном примере событие отправится только на реальном ios устройстве, при этом скомпилируется для Catalyst и симулятора.

```
        #if !targetEnvironment(macCatalyst) && !targetEnvironment(simulator)
        YMMYandexMetrica.reportEvent(event, parameters: parameters) { error in
            print(error.localizedDescription)
        }
        #endif
```

Это конечно уродование кода, но можно сделать обертку над метрикой и перенести все это туда. Тогда выгялдит не так убого

**Comment by GLinnik21** [comment]
> @GLinnik21, добрый день. А как скоро планируете?

Добрый день! Только что выложили релиз с поддержкой
