### ISSUE TITLE
I have trouble with build example project with YandexMobileMetrica on M1 Mac mini for simulator

### ISSUE THREAD

**Issue by iDevPro** [yandexmobile/metrica-sdk-ios#93]
Machine: Mac mini M1 

Package manager: Cocoapods 1.10.1

Build for: Simulator

Error message: Pods/YandexMobileMetrica/ios/static/YandexMobileMetrica.framework/YandexMobileMetrica(YMMKeychainBridge.o), building for iOS Simulator, but linking in object file built for iOS, file /Pods/YandexMobileMetrica/ios/static/YandexMobileMetrica.framework/YandexMobileMetrica for architecture arm64

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12371591. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp21.03.2021, 12:20, "iQQator" ***@***.***>:
Machine: Mac mini M1
Package manager: Cocoapods 1.10.1
Build for: Simulator
Error message: Pods/YandexMobileMetrica/ios/static/YandexMobileMetrica.framework/YandexMobileMetrica(YMMKeychainBridge.o), building for iOS Simulator, but linking in object file built for iOS, file /Pods/YandexMobileMetrica/ios/static/YandexMobileMetrica.framework/YandexMobileMetrica for architecture arm64

**Comment by userich** [comment]
Hi, iDevPro
I have the same issue. Did you get any kind of help for preventing this issue?

**Comment by iDevPro** [comment]
> Hi, iDevPro
> I have the same issue. Did you get any kind of help for preventing this issue?

No, not yet :(

**Comment by GLinnik21** [comment]
Duplicate of https://github.com/yandexmobile/metrica-sdk-ios/issues/92

**Comment by Ivbl95** [comment]
> > Hi, iDevPro
> > I have the same issue. Did you get any kind of help for preventing this issue?
> 
> No, not yet :(

Hello, did you decide the problem?
