### ISSUE TITLE
activateWithConfiguration on Background queue

### ISSUE THREAD

**Issue by Banannzza** [yandexmobile/metrica-sdk-ios#95]
Привет.

На версии 3.16 вызов 
`[YMMYandexMetrica activateWithConfiguration:]`
ведет к 
`Main Thread Checker: UI API called on a background thread: -[WKUserScript initWithSource:injectionTime:forMainFrameOnly:]`

На версии 3.15.1 ошибки нет.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12980645. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp01.06.2021, 15:38, "Aleksey Ostapenko" ***@***.***>:
Привет.
На версии 3.16 вызов
[YMMYandexMetrica activateWithConfiguration:]
ведет к
Main Thread Checker: UI API called on a background thread: -[WKUserScript initWithSource:injectionTime:forMainFrameOnly:]
На версии 3.15.1 ошибки нет.

**Comment by GLinnik21** [comment]
Здравствуйте. Кажется эта проблема должна была починиться в `3.17.0`
