### ISSUE TITLE
Определение активирована ли Appmetrica

### ISSUE THREAD

**Issue by rediska1114** [yandexmobile/metrica-sdk-ios#97]
Здравствуйте! Возможно ли как-то определить, была ли активирована Appmetrica? 

Я пишу несколько плагинов для capacitor и в одном из них (плагин для Appmetrica Push SDK) нужно определить, была ли активирована Appmetrica до этого или нужно активировать ее в плагине.

Возможно ли это как-то определить, и если нет, можете ли добавить такой параметр?

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 13917786. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp07.09.2021, 10:45, "Stepan Kotov" ***@***.***>:
Здравствуйте! Возможно ли как-то определить, была ли активирована Appmetrica?
Я пишу несколько плагинов для capacitor и в одном из них (плагин для Appmetrica Push SDK) нужно определить, была ли активирована Appmetrica до этого или нужно активировать ее в плагине.
Возможно ли это как-то определить, и если нет, можете ли добавить такой параметр?

**Comment by GLinnik21** [comment]
Здравствуйте. Боюсь такого API сейчас наша SDK не предоставляет. SDK можно считать активированной сразу же после вызова `+activateWithConfiguration:`. 
Мы рассмотрим предложение о добавлении такого метода в API.
